DROP TABLE IF EXISTS TBL_EMPLOYEES;
DROP TABLE IF EXISTS TBL_MESSAGES;
  
CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

CREATE TABLE TBL_MESSAGES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sender_id INT,
    FOREIGN KEY (sender_id) REFERENCES TBL_EMPLOYEES(ID),
    recipient_id INT,
    FOREIGN KEY (recipient_id) REFERENCES TBL_EMPLOYEES(ID),
    message_text VARCHAR(2048) DEFAULT NULL,
    message_read BOOLEAN DEFAULT FALSE,
	message_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
