DROP TABLE IF EXISTS TBL_USERS;
DROP TABLE IF EXISTS TBL_MESSAGES;
  
CREATE TABLE TBL_USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(250) NOT NULL,
  description VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

CREATE TABLE TBL_MESSAGES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sender_id INT,
    FOREIGN KEY (sender_id) REFERENCES TBL_USERS(ID),
    recipient_id INT,
    FOREIGN KEY (recipient_id) REFERENCES TBL_USERS(ID),
    message_text VARCHAR(2048) DEFAULT NULL,
    message_read BOOLEAN DEFAULT FALSE,
	message_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
